version: '3'
services:
    app-server:
        image: fs-crud-api
        build: ./api/
        environment: 
            APP_CONFIG: ${APP_CONFIG}
            GOOGLE_APPLICATION_CREDENTIALS: /var/credentials/application_credentials.json
            PROJECT_ID: ${PROJECT_ID}
        volumes:
            - ${DIR}/api:/opt/crud-api
            - ${GOOGLE_APPLICATION_CREDENTIALS}:/var/credentials/application_credentials.json
        sysctls:
            net.core.somaxconn: 10000

    nginx:
        image: fs-crud-nginx
        build: ./nginx/
        links:
            - app-server:app-server
        ports:
            - 80:80
        volumes:
            - ${DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf

    locust:
        image: locust
        build: ./locust/
        links:
            - nginx:nginx
        ports:
            - 8089:8089
        volumes:
            - ${DIR}/locust/src:/opt/locust/src